apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-get-task-api
spec:
  replicas: {{ .Values.get-tasks.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-get-task-api
  template:
    metadata:
      name: {{ .Release.Name }}-todo-get-task
      labels:
        app: {{ .Release.Name }}-todo-get-task-api
    spec:
      containers:
      - name: {{ .Release.Name }}-todo-get-task-api
        image: {{ .Values.common.acr_name }}/{{ .Values.get-tasks.image.image_name }}:{{ .Values.get-tasks.image.tag }}
        ports:
        - containerPort: {{ .Values.get-tasks.ports.containerPort }}
        env: 
        - name: {{ .Values.common.env.name }}
          value: {{ .Values.common.env.value }}

