apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-todo-get-task-api-ingress
spec:
  ingressClassName: {{ .Values.common.ingressClassName }}
  rules:
    - host: {{ .Values.gettasks.rules.host }}
      http:
        paths:
          - pathType: {{ .Values.common.pathType }}
            path: {{ .Values.common.path }}
            backend:
              service:
                name: {{ .Release.Name }}-todo-get-task-api
                port:
                  number: {{ .Values.gettasks.port.number }}
                  
