apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-todo-get-task-api
spec:
  type: {{ .Values.get-tasks.type }}
  selector:
    app: {{ .Release.Name}}-todo-get-task-api
  ports:
    - port: {{ .Values.get-tasks.ports.port }}
      targetPort: {{ .Values.get-tasks.ports.targetPort }}
      
