apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-delete-tasks-api
spec:
  replicas: {{ .Values.delete-tasks.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-delete-tasks-api
  template:
    metadata:
      name: {{ .Release.Name }}-todo-delete-tasks
      labels:
        app: {{ .Release.Name }}-todo-delete-tasks-api
    spec:
      containers:
       - name: {{ .Release.Name }}-todo-delete-tasks-api
         image: {{ .Values.common.acr_name }}/{{ .Values.delete-tasks.image.image_name }}:{{ .Values.delete-tasks.image.tag }}
         ports:
          - containerPort: {{ .Values.delete-tasks.image.ports.containerPort }}
         env: 
           - name: {{ .Values.common.env.name }}
             value: {{ .Values.common.env.value }}
