apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-ui
spec:
  replicas: {{ .Values.todo-ui.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-ui
  template:
    metadata:
      name: {{ .Release.Name }}-todo-ui
      labels:
        app: {{ .Release.Name }}-todo-ui
    spec:
      containers:
      - name: {{ .Release.Name }}-todo-ui
        image: {{ .Values.common.acr_name }}/{{ .Values.todo-ui.image_name }}:{{ .Values.todo-ui.tag }}
        ports:
        - containerPort: {{ .Values.todo-ui.ports.containerPort }}
