apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-ui
spec:
  type: {{ .Values.todo-ui.type }}
  selector:
    app: {{ .Release.Name }}-todo-ui
  ports:
    - port: {{ .Values.todo-ui.ports.port }}
      targetPort: {{ .Values.todo-ui.ports.targetPort }}
