apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-ui
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-todo-ui
  ports:
    - port: {{ .Values.todoui.ports.port }}
      targetPort: {{ .Values.todoui.ports.targetPort }}
